export type GetUserByIdResponseDto = {
  id: number;
  name: string;
  email: string;
  email_verified_at: string | null;
  created_at: string;
  updated_at: string;
  phone_code: string | null;
  phone: string;
  postal_code: string | null;
  address: string;
  country_id: number | null;
  state_id: number | null;
  city_id: number | null;
  roles: number;
  image: string;
  latlong: string;
  gender: string | null;
  wallet_amount: string;
  status: number;
  verification_token: string;
};
